harnessApiVersion: '1.0'
type: BLUE_GREEN
concurrencyStrategy: INFRA
envName: dev-doc
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  notificationGroups:
  - General Store
  userGroupAsExpression: false
phases:
- type: KUBERNETES
  computeProviderName: harness-demo
  daemonSet: false
  infraDefinitionName: Kubernetes Cluster_ harness-demo_DIRECT_Kubernetes_default
  name: Phase 1
  phaseSteps:
  - type: CONTAINER_SETUP
    name: Setup Container
    steps:
    - type: KUBERNETES_SETUP
      name: Blue/Green Service Setup
      properties:
        blueGreen: true
        blueGreenConfig:
          primaryService:
            serviceType: ClusterIP
            protocol: TCP
            port: 80
            targetPort: 8080
          stageService:
            serviceType: ClusterIP
            protocol: TCP
            port: 80
            targetPort: 8080
        replicationControllerName: ${app.name}-${service.name}-${env.name}
        resizeStrategy: RESIZE_NEW_FIRST
    stepsInParallel: false
  - type: CONTAINER_DEPLOY
    name: Deploy Containers
    steps:
    - type: KUBERNETES_DEPLOY
      name: Upgrade Containers
      properties:
        downsizeInstanceCount: 100
        downsizeInstanceUnitType: PERCENTAGE
        instanceCount: 100
        instanceUnitType: PERCENTAGE
    stepsInParallel: false
  - type: VERIFY_SERVICE
    name: Verify Stage Service
    stepsInParallel: false
  - type: ROUTE_UPDATE
    name: Route Update
    steps:
    - type: KUBERNETES_SWAP_SERVICE_SELECTORS
      name: Swap Primary with Stage
      properties:
        service1: ${PRIMARY_SERVICE_NAME}
        service2: ${STAGE_SERVICE_NAME}
    stepsInParallel: false
  - type: WRAP_UP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: Docker-service
  statefulSet: false
rollbackPhases:
- type: KUBERNETES
  computeProviderName: harness-demo
  daemonSet: false
  infraDefinitionName: Kubernetes Cluster_ harness-demo_DIRECT_Kubernetes_default
  name: Rollback Phase 1
  phaseNameForRollback: Phase 1
  phaseSteps:
  - type: ROUTE_UPDATE
    name: Route Update
    phaseStepNameForRollback: Route Update
    steps:
    - type: KUBERNETES_SWAP_SERVICE_SELECTORS
      name: Swap Primary with Stage
      properties:
        service1: ${PRIMARY_SERVICE_NAME}
        service2: ${STAGE_SERVICE_NAME}
    stepsInParallel: false
  - type: CONTAINER_DEPLOY
    name: Deploy Containers
    phaseStepNameForRollback: Deploy Containers
    statusForRollback: SUCCESS
    stepsInParallel: false
  - type: CONTAINER_SETUP
    name: Setup Container
    phaseStepNameForRollback: Setup Container
    statusForRollback: SUCCESS
    stepsInParallel: false
  - type: VERIFY_SERVICE
    name: Verify Service
    phaseStepNameForRollback: Deploy Containers
    statusForRollback: SUCCESS
    stepsInParallel: false
  - type: WRAP_UP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: Docker-service
  statefulSet: false
templatized: false
