harnessApiVersion: '1.0'
type: BUILD
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  notificationGroups:
  - General Store
  userGroupAsExpression: false
phases:
- daemonSet: false
  name: Phase 1
  phaseSteps:
  - type: PREPARE_STEPS
    name: Prepare Steps
    steps:
    - type: EMAIL
      name: Email
      properties:
        body: |-
          <h1>bar</h1>

          ${workflow.displayName}
        ccAddress: ''
        ignoreDeliveryFailure: false
        subject: test
        templateUuid: null
        templateVariables: null
        templateVersion: null
        toAddress: 'michael.cretzman@harness.io '
    stepsInParallel: false
  - type: COLLECT_ARTIFACT
    name: Collect Artifact
    stepsInParallel: false
  - type: WRAP_UP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  statefulSet: false
templatized: false
