harnessApiVersion: '1.0'
type: BUILD
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  notificationGroups:
  - General Store
  userGroupAsExpression: false
phases:
- daemonSet: false
  name: Phase 1
  phaseSteps:
  - type: PREPARE_STEPS
    name: Prepare Steps
    steps:
    - type: EMAIL
      name: Email
      properties:
        body: |-
          Testing email variables:

          <ul>
          <li>${app.name}</li>
          <li>${workflow.displayName}</li>
          <li>${deploymentUrl}</li>
          </ul>
        ccAddress: ''
        ignoreDeliveryFailure: false
        subject: testing
        templateUuid: null
        templateVariables: null
        templateVersion: null
        toAddress: 'michael.cretzman@harness.io '
    - type: COMMAND
      name: Sagemaker
      properties:
        commandName: Sagemaker
        commandType: OTHER
        connectionAttributes: null
        executeOnDelegate: true
        host: null
        outputVars: ''
        publishAsVar: false
        sshKeyRef: null
        sweepingOutputName: null
        sweepingOutputScope: null
        templateExpressions: null
        timeoutMillis: 60000
      templateUri: General Store Inc/Sagemaker:latest
      templateVariables:
      - name: deploy_instance_count
      - name: deploy_instance_type
      - name: train_instance_count
      - name: train_instance_type
      - name: deploy_endpoint_name
      - name: train_image_name
    stepsInParallel: false
  - type: COLLECT_ARTIFACT
    name: Collect Artifact
    stepsInParallel: false
  - type: WRAP_UP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  statefulSet: false
templatized: false
