harnessApiVersion: '1.0'
type: BASIC
concurrencyStrategy: INFRA
envName: dev
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  notificationGroups:
  - General Store
  userGroupAsExpression: false
phases:
- type: HELM
  computeProviderName: harness-exploration-gcp
  daemonSet: false
  infraDefinitionName: dev-catalog
  name: Phase 1
  phaseSteps:
  - type: HELM_DEPLOY
    name: Deploy Containers
    steps:
    - type: HELM_DEPLOY
      name: Helm Deploy
      properties:
        gitFileConfig:
          connectorId: null
          commitId: null
          branch: null
          useBranch: false
        helmReleaseNamePrefix: ${service.name}-${env.name}-${infra.helm.shortId}
        steadyStateTimeout: 10
    stepsInParallel: false
  - type: VERIFY_SERVICE
    name: Verify Service
    stepsInParallel: false
  - type: WRAP_UP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: catalog
  statefulSet: false
  templateExpressions:
  - expression: ${InfraDefinition_HELM}
    fieldName: infraDefinitionId
    metadata:
    - name: artifactType
      value: DOCKER
    - name: relatedField
    - name: entityType
      value: INFRASTRUCTURE_DEFINITION
rollbackPhases:
- type: HELM
  computeProviderName: harness-exploration-gcp
  daemonSet: false
  infraDefinitionName: dev-catalog
  name: Rollback Phase 1
  phaseNameForRollback: Phase 1
  phaseSteps:
  - type: HELM_DEPLOY
    name: Deploy Containers
    phaseStepNameForRollback: Deploy Containers
    statusForRollback: SUCCESS
    steps:
    - type: HELM_ROLLBACK
      name: Helm Rollback
    stepsInParallel: false
  - type: VERIFY_SERVICE
    name: Verify Service
    phaseStepNameForRollback: Deploy Containers
    statusForRollback: SUCCESS
    stepsInParallel: false
  - type: WRAP_UP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: catalog
  statefulSet: false
  templateExpressions:
  - expression: ${InfraDefinition_HELM}
    fieldName: infraDefinitionId
    metadata:
    - name: artifactType
      value: DOCKER
    - name: relatedField
    - name: entityType
      value: INFRASTRUCTURE_DEFINITION
templateExpressions:
- expression: ${Environment}
  fieldName: envId
  metadata:
  - name: artifactType
    value: DOCKER
  - name: relatedField
  - name: entityType
    value: ENVIRONMENT
- expression: ${InfraDefinition_HELM}
  fieldName: infraDefinitionId
  metadata:
  - name: artifactType
    value: DOCKER
  - name: relatedField
  - name: entityType
    value: INFRASTRUCTURE_DEFINITION
templatized: true
userVariables:
- type: ENTITY
  description: Variable for Environment entity
  fixed: false
  mandatory: true
  name: Environment
- type: ENTITY
  fixed: false
  mandatory: true
  name: InfraDefinition_HELM
