harnessApiVersion: '1.0'
type: PIPELINE
pipelineStages:
- type: ENV_STATE
  name: Dev GCP Docker Workflow (Development)
  parallel: false
  skipCondition:
    type: DO_NOT_SKIP
  workflowName: Dev GCP Docker Workflow
- type: APPROVAL
  name: Approval 1
  parallel: false
  skipCondition:
    type: DO_NOT_SKIP
- type: ENV_STATE
  name: Canary Test (Development)
  parallel: false
  skipCondition:
    type: DO_NOT_SKIP
  workflowName: Canary Test
