harnessApiVersion: '1.0'
type: ROLLING
concurrencyStrategy: INFRA
envName: Development
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - SUCCESS
  - FAILED
  - PAUSED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - 9gBB_2hwQWqDyiCI7H-o5g
phases:
- type: KUBERNETES
  computeProviderName: harness-demo
  daemonSet: false
  name: Rolling
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Pre-Deployment
    steps:
    - type: JIRA_CREATE_UPDATE
      name: Create Jira
      properties:
        description: "Deployment url : ${deploymentUrl}\nArtifact: ${artifact.displayName}\n\
          Build number: ${artifact.buildNo} "
        issueType: Story
        jiraAction: CREATE_TICKET
        jiraConnectorId: iGQfgpbFSQiEzDVYUf5CiA
        labels:
        - deployment
        priority: P2
        project: HD
        publishAsVar: true
        summary: Ticket to track deployment for ${pipeline.name}
        sweepingOutputName: Jiravar
        sweepingOutputScope: PIPELINE
    - type: HTTP
      name: Custom Test
      properties:
        assertion: ''
        body: ''
        executeWithPreviousSteps: false
        header: ''
        method: GET
        publishAsVar: false
        responseProcessingExpressions: ''
        sweepingOutputName: null
        sweepingOutputScope: null
        templateVariables: ''
        timeoutMillis: 10000
        url: https://harness.io
    - type: HTTP
      name: Verify Fortify Scan
      properties:
        assertion: ''
        body: ''
        executeWithPreviousSteps: false
        header: ''
        method: GET
        publishAsVar: false
        responseProcessingExpressions: ''
        sweepingOutputName: null
        sweepingOutputScope: null
        templateVariables: ''
        timeoutMillis: 10000
        url: https://harness.io
    - type: HTTP
      name: Security Analyses
      properties:
        assertion: ''
        body: ''
        executeWithPreviousSteps: false
        header: ''
        method: GET
        publishAsVar: false
        responseProcessingExpressions: ''
        sweepingOutputName: null
        sweepingOutputScope: null
        templateUuid: null
        templateVariables: null
        templateVersion: null
        timeoutMillis: 10000
        url: https://harness.io
    - type: JIRA_CREATE_UPDATE
      name: Jira Update
      properties:
        comment: Custom Test, Verify Fortify Scan, and Veracode Security Analysis all ran successfully
        customFields: null
        issueId: ${Jiravar.issueId}
        jiraAction: UPDATE_TICKET
        jiraConnectorId: iGQfgpbFSQiEzDVYUf5CiA
        labels:
        - ''
        project: HD
        status: In Progress
    stepsInParallel: false
    waitInterval: 0
  - type: K8S_PHASE_STEP
    name: Deploy
    steps:
    - type: K8S_DEPLOYMENT_ROLLING
      name: Rollout Deployment
    stepsInParallel: false
  provisionNodes: false
  serviceName: Order V2
  statefulSet: false
rollbackPhases:
- type: KUBERNETES
  computeProviderName: harness-demo
  daemonSet: false
  name: Rollback Rolling
  phaseNameForRollback: Rolling
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    phaseStepNameForRollback: Deploy
    statusForRollback: SUCCESS
    steps:
    - type: K8S_DEPLOYMENT_ROLLING_ROLLBACK
      name: Rollback Deployment
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    phaseStepNameForRollback: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: Order V2
  statefulSet: false
templatized: false
