harnessApiVersion: '1.0'
type: CANARY
concurrencyStrategy: INFRA
envName: Production
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - comU8qGHTi6WxK8sb1nZjA
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - Elp1y6mUQjKnTCFKoie_KQ
- conditions:
  - SUCCESS
  - FAILED
  - PAUSED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - 9gBB_2hwQWqDyiCI7H-o5g
- conditions:
  - SUCCESS
  - FAILED
  - PAUSED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - YHTEfNFuSCqWjTW2G1BiOw
phases:
- type: KUBERNETES
  computeProviderName: harness-demo
  daemonSet: false
  infraDefinitionName: Order V2
  name: Canary Phase 1
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    steps:
    - type: K8S_CANARY_DEPLOY
      name: Canary Deployment
      properties:
        instanceUnitType: COUNT
        instances: '2'
        stateTimeoutInMinutes: 10
        templateUuid: null
        templateVariables: null
        templateVersion: null
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    steps:
    - type: APP_DYNAMICS
      name: AppDynamics
      properties:
        analysisServerConfigId: BOMCiZpNS9akFuShvfADhw
        analysisTolerance: LOW
        applicationId: '7596'
        comparisonStrategy: COMPARE_WITH_PREVIOUS
        dependentTiersToAnalyze: null
        executeWithPreviousSteps: false
        includeTiers: false
        predictiveHistoryMinutes: ''
        templateExpressions: null
        templateUuid: null
        templateVariables: null
        templateVersion: null
        tierId: '147416'
        timeDuration: 15
    - type: NEW_RELIC
      name: NewRelic
      properties:
        analysisServerConfigId: hJKKzAjmS5iWVhWaE2ELHA
        analysisTolerance: LOW
        applicationId: '117116134'
        comparisonStrategy: COMPARE_WITH_PREVIOUS
        executeWithPreviousSteps: false
        includePreviousPhaseNodes: false
        predictiveHistoryMinutes: ''
        templateUuid: null
        templateVariables: null
        templateVersion: null
        timeDuration: 15
    - type: PROMETHEUS
      name: Prometheus
      properties:
        analysisServerConfigId: H84fzJkTRceykoF5pgxvmg
        analysisTolerance: LOW
        comparisonStrategy: COMPARE_WITH_PREVIOUS
        executeWithPreviousSteps: false
        includePreviousPhaseNodes: false
        timeDuration: '15'
        timeSeriesToAnalyze:
        - txnName: Hardware
          metricName: CPU
          metricType: ERROR
          url: /api/v1/query_range?start=$startTime&end=$endTime&step=60s&query=container_cpu_usage_seconds_total{pod_name="$hostName"}
        - txnName: Hardware
          metricName: Container memory usage
          metricType: THROUGHPUT
          url: /api/v1/query_range?start=$startTime&end=$endTime&step=60s&query=container_memory_usage_bytes{pod_name="$hostName"}
    - type: APM_VERIFICATION
      name: APM Verification
      properties:
        analysisServerConfigId: Z9VxfmRJQ66HMlsy69MwrA
        comparisonStrategy: COMPARE_WITH_PREVIOUS
        dataCollectionRate: '3'
        includePreviousPhaseNodes: false
        metricCollectionInfos:
        - metricName: CustomKubeMemoryPct
          metricType: INFRA
          tag: CustomKubeMemory
          collectionUrl: query?query=kubernetes.memory.usage_pct{pod_name:${host}}by{pod_name}.rollup(avg,60)&from=${start_time_seconds}&to=${end_time_seconds}
          responseType: json
          method: GET
          responseMapping:
            txnNameFieldValue: KubeMemory
            metricValueJsonPath: series[*].pointlist[*].[1]
            timestampJsonPath: series[*].pointlist[*].[0]
        timeDuration: '8'
        tolerance: LOW
    - type: ELK
      name: ELK
      properties:
        analysisServerConfigId: HcLTA7-7TSKsCsVRJOpfIA
        hostnameField: host
        indices: filebeat-*
        messageField: message
        query: error
        queryType: TERM
        timestampField: '@timestamp'
        timestampFormat: yyyy-MM-dd'T'HH:mm:ss.SSSX
    - type: CLOUD_WATCH
      name: CloudWatch
      properties:
        analysisServerConfigId: K7BS1kPySSaK_l3WvDwCUw
        analysisTolerance: LOW
        comparisonStrategy: COMPARE_WITH_PREVIOUS
        ec2Metrics: null
        executeWithPreviousSteps: false
        loadBalancerMetrics: null
        region: us-east-1
        shouldDoLambdaVerification: true
        timeDuration: 10
    - type: SPLUNKV2
      name: Splunkv2
      properties:
        analysisServerConfigId: wT3iJqyzQvWi7jkENhxjdw
        analysisTolerance: MEDIUM
        comparisonStrategy: COMPARE_WITH_PREVIOUS
        executeWithPreviousSteps: false
        hostnameField: host
        hostnameTemplate: ${host.hostName}
        isAdvancedQuery: false
        query: '*exception*'
        templateUuid: null
        templateVariables: null
        templateVersion: null
        timeDuration: '10'
    - type: DATA_DOG
      name: Datadog
      properties:
        analysisServerConfigId: loF3pB2cQciFuHiklL6APA
        analysisTolerance: LOW
        comparisonStrategy: COMPARE_WITH_PREVIOUS
        datadogServiceName: Test Service
        executeWithPreviousSteps: false
        metrics: docker.cpu.throttled,docker.cpu.usage,docker.mem.rss
    - type: DYNA_TRACE
      name: Dynatrace
      properties:
        analysisServerConfigId: 32WrL8u2TNK3GGaXag1aiw
        analysisTolerance: LOW
        comparisonStrategy: COMPARE_WITH_PREVIOUS
        executeWithPreviousSteps: true
        serviceMethods: SERVICE_METHOD-991CE862F114C79F
        timeDuration: 15
    stepsInParallel: true
    waitInterval: 5
  provisionNodes: false
  serviceName: Order V2
  statefulSet: false
- type: KUBERNETES
  computeProviderName: harness-demo
  daemonSet: false
  infraDefinitionName: Order V2
  name: Canary Phase 2
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    steps:
    - type: K8S_SCALE
      name: Scale Canary
      properties:
        instanceUnitType: COUNT
        instances: '4'
        stateTimeoutInMinutes: 10
        templateUuid: null
        templateVariables: null
        templateVersion: null
        workload: ${k8s.canaryWorkload}
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    stepsInParallel: true
    waitInterval: 0
  provisionNodes: false
  serviceName: Order V2
  statefulSet: false
- type: KUBERNETES
  computeProviderName: harness-demo
  daemonSet: false
  infraDefinitionName: Order V2
  name: Primary Rollout
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    steps:
    - type: K8S_DEPLOYMENT_ROLLING
      name: Rollout Deployment
      properties:
        stateTimeoutInMinutes: 10
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    steps:
    - type: APP_DYNAMICS
      name: AppDynamics
      properties:
        analysisServerConfigId: 2pd6OJV5Rqe2ciI3jM0y4g
        analysisTolerance: LOW
        applicationId: '7596'
        comparisonStrategy: COMPARE_WITH_PREVIOUS
        dependentTiersToAnalyze: null
        executeWithPreviousSteps: false
        includeTiers: false
        tierId: '147416'
        timeDuration: '15'
    - type: NEW_RELIC
      name: NewRelic
      properties:
        analysisServerConfigId: VEMGQArgSYmKyboSKpFx7A
        analysisTolerance: LOW
        applicationId: '117116134'
        comparisonStrategy: COMPARE_WITH_PREVIOUS
        executeWithPreviousSteps: false
        includePreviousPhaseNodes: false
        timeDuration: '15'
    - type: PROMETHEUS
      name: Prometheus
      properties:
        analysisServerConfigId: D4c-nj43TJ6cBjwacjnmQg
        analysisTolerance: LOW
        comparisonStrategy: COMPARE_WITH_PREVIOUS
        executeWithPreviousSteps: false
        includePreviousPhaseNodes: false
        timeDuration: '15'
        timeSeriesToAnalyze:
        - txnName: Hardware
          metricName: CPU
          metricType: ERROR
          url: /api/v1/query_range?start=$startTime&end=$endTime&step=60s&query=container_cpu_usage_seconds_total{pod_name="$hostName"}
        - txnName: Hardware
          metricName: Container memory usage
          metricType: THROUGHPUT
          url: /api/v1/query_range?start=$startTime&end=$endTime&step=60s&query=container_memory_usage_bytes{pod_name="$hostName"}
    - type: APM_VERIFICATION
      name: APM Verification
      properties:
        analysisServerConfigId: 8pdQDNUvTCCHmLcUUTaQcg
        comparisonStrategy: COMPARE_WITH_PREVIOUS
        dataCollectionRate: '3'
        includePreviousPhaseNodes: false
        metricCollectionInfos:
        - metricName: CustomKubeMemoryPct
          metricType: INFRA
          tag: CustomKubeMemory
          collectionUrl: query?query=kubernetes.memory.usage_pct{pod_name:${host}}by{pod_name}.rollup(avg,60)&from=${start_time_seconds}&to=${end_time_seconds}
          responseType: json
          method: GET
          responseMapping:
            txnNameFieldValue: KubeMemory
            metricValueJsonPath: series[*].pointlist[*].[1]
            timestampJsonPath: series[*].pointlist[*].[1]
        timeDuration: '8'
        tolerance: LOW
    - type: ELK
      name: ELK
      properties:
        analysisServerConfigId: HtdcnW_RS5y1BEOa2WW6dQ
        hostnameField: host
        indices: filebeat-*
        messageField: log
        query: error
        queryType: TERM
        timestampField: '@timestamp'
        timestampFormat: yyyy-MM-dd'T'HH:mm:ss.SSSX
    - type: CLOUD_WATCH
      name: CloudWatch
      properties:
        analysisServerConfigId: w2T-JlMnSIO17xJ7gKoKSw
        analysisTolerance: LOW
        comparisonStrategy: COMPARE_WITH_PREVIOUS
        ec2Metrics: null
        executeWithPreviousSteps: false
        loadBalancerMetrics: null
        region: us-east-1
        shouldDoLambdaVerification: true
        timeDuration: 0
    - type: SPLUNKV2
      name: Splunkv2
      properties:
        analysisServerConfigId: E8ZFr1eJRPWPKuKKZq3ebw
        analysisTolerance: MEDIUM
        comparisonStrategy: COMPARE_WITH_PREVIOUS
        hostnameField: host
        query: '*exception*'
        timeDuration: '15'
    - type: DATA_DOG
      name: Datadog
      properties:
        analysisServerConfigId: d0s23pTARqCCSJGP0w5Cyw
        analysisTolerance: LOW
        comparisonStrategy: COMPARE_WITH_PREVIOUS
        datadogServiceName: Test Service
        executeWithPreviousSteps: false
        metrics: docker.cpu.throttled,docker.cpu.usage,docker.mem.rss
    - type: DYNA_TRACE
      name: Dynatrace
      properties:
        analysisServerConfigId: Oz_oQTqlRYGS3VhKPNko8w
        analysisTolerance: LOW
        comparisonStrategy: COMPARE_WITH_PREVIOUS
        executeWithPreviousSteps: true
        serviceMethods: SERVICE_METHOD-991CE862F114C79F
        timeDuration: 15
    stepsInParallel: true
    waitInterval: 0
  - type: K8S_PHASE_STEP
    name: Wrap Up
    steps:
    - type: K8S_DELETE
      name: Delete Canary
      properties:
        deleteNamespacesForRelease: false
        resources: ${k8s.canaryWorkload}
    stepsInParallel: false
  provisionNodes: false
  serviceName: Order V2
  statefulSet: false
rollbackPhases:
- type: KUBERNETES
  computeProviderName: harness-demo
  daemonSet: false
  infraDefinitionName: Order V2
  name: Rollback Canary Phase 1
  phaseNameForRollback: Canary Phase 1
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    phaseStepNameForRollback: Deploy
    statusForRollback: SUCCESS
    steps:
    - type: K8S_DELETE
      name: Delete Canary
      properties:
        deleteNamespacesForRelease: false
        resources: ${k8s.canaryWorkload}
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    phaseStepNameForRollback: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: Order V2
  statefulSet: false
- type: KUBERNETES
  computeProviderName: harness-demo
  daemonSet: false
  infraDefinitionName: Order V2
  name: Rollback Canary Phase 2
  phaseNameForRollback: Canary Phase 2
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    phaseStepNameForRollback: Deploy
    statusForRollback: SUCCESS
    steps:
    - type: K8S_SCALE
      name: Scale
      properties:
        instanceUnitType: COUNT
        instances: '2'
        stateTimeoutInMinutes: 10
        workload: ${k8s.canaryWorkload}
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    phaseStepNameForRollback: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: Order V2
  statefulSet: false
- type: KUBERNETES
  computeProviderName: harness-demo
  daemonSet: false
  infraDefinitionName: Order V2
  name: Rollback Primary Rollout
  phaseNameForRollback: Primary Rollout
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    phaseStepNameForRollback: Deploy
    statusForRollback: SUCCESS
    steps:
    - type: K8S_DEPLOYMENT_ROLLING_ROLLBACK
      name: Rollback Deployment
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    phaseStepNameForRollback: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: Order V2
  statefulSet: false
templatized: false
