harnessApiVersion: '1.0'
type: CANARY
concurrencyStrategy: INFRA
envName: Production
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  - VERIFICATION_FAILURE
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
- executionScope: WORKFLOW
  failureTypes:
  - CONNECTIVITY
  - AUTHENTICATION
  repairActionCode: MANUAL_INTERVENTION
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - comU8qGHTi6WxK8sb1nZjA
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - Elp1y6mUQjKnTCFKoie_KQ
- conditions:
  - SUCCESS
  - FAILED
  - PAUSED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - 9gBB_2hwQWqDyiCI7H-o5g
- conditions:
  - SUCCESS
  - FAILED
  - PAUSED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - YHTEfNFuSCqWjTW2G1BiOw
phases:
- type: KUBERNETES
  computeProviderName: harness-demo
  daemonSet: false
  infraDefinitionName: Order V2
  name: Canary - 25%
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    steps:
    - type: K8S_CANARY_DEPLOY
      name: Canary Deployment
      properties:
        instanceUnitType: COUNT
        instances: '2'
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    steps:
    - type: NEW_RELIC
      name: NewRelic
      properties:
        analysisServerConfigId: hJKKzAjmS5iWVhWaE2ELHA
        analysisTolerance: LOW
        applicationId: '117116134'
        comparisonStrategy: COMPARE_WITH_PREVIOUS
        executeWithPreviousSteps: false
        includePreviousPhaseNodes: false
        predictiveHistoryMinutes: ''
        templateUuid: null
        templateVariables: null
        templateVersion: null
        timeDuration: 15
    stepsInParallel: true
    waitInterval: 5
  - type: K8S_PHASE_STEP
    name: Wrap Up
    steps:
    - type: K8S_DELETE
      name: Canary Delete
      properties:
        instanceUnitType: COUNT
        resources: ${k8s.canaryWorkload}
    stepsInParallel: false
    waitInterval: 5
  provisionNodes: false
  serviceName: Order V2
  statefulSet: false
- type: KUBERNETES
  computeProviderName: harness-demo
  daemonSet: false
  infraDefinitionName: Order V2
  name: Rollout - Full Prod
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    steps:
    - type: K8S_DEPLOYMENT_ROLLING
      name: Rollout Deployment
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    steps:
    - type: NEW_RELIC
      name: NewRelic
      properties:
        analysisServerConfigId: VEMGQArgSYmKyboSKpFx7A
        analysisTolerance: LOW
        applicationId: '117116134'
        comparisonStrategy: COMPARE_WITH_PREVIOUS
        executeWithPreviousSteps: false
        includePreviousPhaseNodes: false
        timeDuration: '15'
    stepsInParallel: true
    waitInterval: 0
  - type: K8S_PHASE_STEP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: Order V2
  statefulSet: false
preDeploymentSteps:
- type: JIRA_CREATE_UPDATE
  name: Jira
  properties:
    customFields: null
    issueType: Test
    jiraAction: CREATE_TICKET
    jiraConnectorId: iGQfgpbFSQiEzDVYUf5CiA
    labels:
    - ''
    project: HD
    summary: Paul Workflow Test
templatized: false
