harnessApiVersion: '1.0'
type: CANARY
concurrencyStrategy: INFRA
envName: Production
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  - VERIFICATION_FAILURE
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
- actionAfterTimeout: END_EXECUTION
  executionScope: WORKFLOW
  failureTypes:
  - CONNECTIVITY
  - AUTHENTICATION
  manualInterventionTimeout: 1209600000
  repairActionCode: MANUAL_INTERVENTION
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - comU8qGHTi6WxK8sb1nZjA
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - Elp1y6mUQjKnTCFKoie_KQ
- conditions:
  - SUCCESS
  - FAILED
  - PAUSED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - 9gBB_2hwQWqDyiCI7H-o5g
- conditions:
  - SUCCESS
  - FAILED
  - PAUSED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - YHTEfNFuSCqWjTW2G1BiOw
phases:
- type: KUBERNETES
  computeProviderName: harness-demo
  daemonSet: false
  infraDefinitionName: Order V2
  name: Canary - 25%
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    steps:
    - type: K8S_CANARY_DEPLOY
      name: Canary Deployment
      properties:
        instanceUnitType: COUNT
        instances: '2'
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    steps:
    - type: APP_DYNAMICS
      name: AppDynamics
      properties:
        analysisServerConfigId: BOMCiZpNS9akFuShvfADhw
        analysisTolerance: LOW
        applicationId: '7596'
        comparisonStrategy: COMPARE_WITH_PREVIOUS
        dependentTiersToAnalyze: null
        executeWithPreviousSteps: false
        includeTiers: false
        predictiveHistoryMinutes: ''
        templateExpressions: null
        templateUuid: null
        templateVariables: null
        templateVersion: null
        tierId: '147416'
        timeDuration: 15
    stepsInParallel: true
    waitInterval: 5
  - type: K8S_PHASE_STEP
    name: Wrap Up
    steps:
    - type: K8S_DELETE
      name: Canary Delete
      properties:
        instanceUnitType: COUNT
        resources: ${k8s.canaryWorkload}
    stepsInParallel: false
    waitInterval: 5
  provisionNodes: false
  serviceName: Order V2
  statefulSet: false
  templateExpressions:
  - expression: ${Service}
    fieldName: serviceId
    metadata:
    - name: relatedField
      value: ${InfraDefinition_Kubernetes}
    - name: artifactType
      value: DOCKER
    - name: entityType
      value: SERVICE
  - expression: ${InfraDefinition_Kubernetes}
    fieldName: infraDefinitionId
    metadata:
    - name: artifactType
      value: DOCKER
    - name: entityType
      value: INFRASTRUCTURE_DEFINITION
- type: KUBERNETES
  computeProviderName: harness-demo
  daemonSet: false
  infraDefinitionName: Order V2
  name: Rollout - Full Prod
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    steps:
    - type: K8S_DEPLOYMENT_ROLLING
      name: Rollout Deployment
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    steps:
    - type: APP_DYNAMICS
      name: AppDynamics
      properties:
        analysisServerConfigId: 2pd6OJV5Rqe2ciI3jM0y4g
        analysisTolerance: LOW
        applicationId: '7596'
        comparisonStrategy: COMPARE_WITH_PREVIOUS
        dependentTiersToAnalyze: null
        executeWithPreviousSteps: false
        includeTiers: false
        tierId: '147416'
        timeDuration: '15'
    stepsInParallel: true
    waitInterval: 0
  - type: K8S_PHASE_STEP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: Order V2
  statefulSet: false
  templateExpressions:
  - expression: ${InfraDefinition_Kubernetes2}
    fieldName: infraDefinitionId
    metadata:
    - name: artifactType
      value: DOCKER
    - name: entityType
      value: INFRASTRUCTURE_DEFINITION
preDeploymentSteps:
- type: JIRA_CREATE_UPDATE
  name: Jira
  properties:
    customFields: null
    issueType: Test
    jiraAction: CREATE_TICKET
    jiraConnectorId: iGQfgpbFSQiEzDVYUf5CiA
    labels:
    - ''
    project: HD
    summary: Paul Workflow Test
templateExpressions:
- expression: ${Environment}
  fieldName: envId
  metadata:
  - name: relatedField
  - name: entityType
    value: ENVIRONMENT
templatized: true
userVariables:
- type: ENTITY
  description: Variable for Environment entity
  fixed: false
  mandatory: true
  name: Environment
- type: ENTITY
  description: Variable for Service entity in Canary - 25%
  fixed: false
  mandatory: true
  name: Service
- type: ENTITY
  description: Variable for Infrastructure Definition entity in Canary - 25%
  fixed: false
  mandatory: true
  name: InfraDefinition_Kubernetes
- type: ENTITY
  description: Variable for Infrastructure Definition entity in Rollout - Full Prod
  fixed: false
  mandatory: true
  name: InfraDefinition_Kubernetes2
