harnessApiVersion: '1.0'
type: CANARY
concurrencyStrategy: INFRA
envName: Production
failureStrategies:
- actionAfterTimeout: END_EXECUTION
  executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  - VERIFICATION_FAILURE
  manualInterventionTimeout: 1209600000
  repairActionCode: MANUAL_INTERVENTION
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  notificationGroups:
  - Account Administrator
  userGroupAsExpression: false
  userGroupIds:
  - GXFtTUS2Q9Gmo1r4MhqS4g
phases:
- type: KUBERNETES
  computeProviderName: harness-demo
  daemonSet: false
  infraDefinitionName: Prod harness-demo cluster
  name: Phase 1
  phaseSteps:
  - type: CONTAINER_SETUP
    name: Setup Container
    steps:
    - type: KUBERNETES_SETUP
      name: Kubernetes Service Setup
      properties:
        className: software.wings.sm.states.KubernetesSetup
        commandName: Setup Replication Controller
        replicationControllerName: ${app.name}.${service.name}.${env.name}
    stepsInParallel: false
  - type: CONTAINER_DEPLOY
    name: Deploy Containers
    steps:
    - type: KUBERNETES_DEPLOY
      name: Upgrade Containers
      properties:
        className: software.wings.sm.states.KubernetesDeploy
        commandName: Resize Replication Controller
        instanceCount: 2
    stepsInParallel: false
  - type: VERIFY_SERVICE
    name: Verify Service
    steps:
    - type: SPLUNK
      name: Splunk
      properties:
        assertion: ' '
        query: sourcetype=access_combined_wcookie
        waitInterval: 20
    - type: HTTP
      name: AppDynamics
      properties:
        method: GET
        url: http://go.com
    stepsInParallel: true
  provisionNodes: false
  serviceName: Order
  statefulSet: false
- type: KUBERNETES
  computeProviderName: harness-demo
  daemonSet: false
  infraDefinitionName: Prod harness-demo cluster
  name: Phase 2
  phaseSteps:
  - type: CONTAINER_DEPLOY
    name: Deploy Containers
    steps:
    - type: KUBERNETES_DEPLOY
      name: Upgrade Containers
      properties:
        className: software.wings.sm.states.KubernetesDeploy
        commandName: Resize Replication Controller
        instanceCount: 4
    stepsInParallel: false
  - type: VERIFY_SERVICE
    name: Verify Service
    steps:
    - type: SPLUNK
      name: Splunk
      properties:
        assertion: ${xpath('/results/result[1]/field[@k="host"]/value/text/text()')}!=null
        query: sourcetype=access_combined_wcookie
    - type: HTTP
      name: AppDynamics
      properties:
        method: GET
        url: http://go.com
    - type: HTTP
      name: Fail on Purpose
      properties:
        method: GET
        url: https://go.com
    stepsInParallel: true
  provisionNodes: false
  serviceName: Order
  statefulSet: false
rollbackPhases:
- type: KUBERNETES
  computeProviderName: harness-demo
  daemonSet: false
  infraDefinitionName: Prod harness-demo cluster
  name: Rollback Phase 1
  phaseNameForRollback: Phase 1
  phaseSteps:
  - type: CONTAINER_DEPLOY
    name: Deploy Containers
    phaseStepNameForRollback: Deploy Containers
    statusForRollback: SUCCESS
    steps:
    - type: KUBERNETES_DEPLOY_ROLLBACK
      name: Rollback Containers
      properties:
        className: software.wings.sm.states.KubernetesDeployRollback
        rollback: true
    stepsInParallel: false
  - type: VERIFY_SERVICE
    name: Verify Service
    phaseStepNameForRollback: Verify Service
    statusForRollback: SUCCESS
    stepsInParallel: false
  provisionNodes: false
  serviceName: Order
  statefulSet: false
- type: KUBERNETES
  computeProviderName: harness-demo
  daemonSet: false
  infraDefinitionName: Prod harness-demo cluster
  name: Rollback Phase 2
  phaseNameForRollback: Phase 2
  phaseSteps:
  - type: CONTAINER_DEPLOY
    name: Deploy Containers
    phaseStepNameForRollback: Deploy Containers
    statusForRollback: SUCCESS
    steps:
    - type: KUBERNETES_DEPLOY_ROLLBACK
      name: Rollback Containers
      properties:
        className: software.wings.sm.states.KubernetesDeployRollback
        rollback: true
    stepsInParallel: false
  - type: VERIFY_SERVICE
    name: Verify Service
    phaseStepNameForRollback: Verify Service
    statusForRollback: SUCCESS
    stepsInParallel: false
  provisionNodes: false
  serviceName: Order
  statefulSet: false
templatized: false
