harnessApiVersion: '1.0'
type: CANARY
concurrencyStrategy: INFRA
envName: Production
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  - VERIFICATION_FAILURE
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
- executionScope: WORKFLOW
  failureTypes:
  - VERIFICATION_FAILURE
  - CONNECTIVITY
  repairActionCode: MANUAL_INTERVENTION
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  notificationGroups:
  - Account Administrator
  userGroupAsExpression: false
  userGroupIds:
  - GXFtTUS2Q9Gmo1r4MhqS4g
- conditions:
  - SUCCESS
  - FAILED
  - PAUSED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - 3WCd71Y2SC-vYGSjqJp0zA
phases:
- type: KUBERNETES
  computeProviderName: harness-demo
  daemonSet: false
  infraDefinitionName: Prod harness-demo cluster
  name: Phase 1
  phaseSteps:
  - type: CONTAINER_SETUP
    name: Setup Container
    steps:
    - type: KUBERNETES_SETUP
      name: Kubernetes Service Setup
      properties:
        className: software.wings.sm.states.KubernetesSetup
        commandName: Setup Replication Controller
        desiredInstanceCount: fixedInstances
        fixedInstances: '6'
        istioConfig: null
        maxAutoscaleInstances: 0
        maxInstances: 2
        minAutoscaleInstances: 0
        replicationControllerName: ${app.name}.${service.name}.${env.name}
        resizeStrategy: DOWNSIZE_OLD_FIRST
        serviceSteadyStateTimeout: 10
        serviceType: None
        targetCpuUtilizationPercentage: 0
        useAutoscaler: false
    stepsInParallel: false
  - type: CONTAINER_DEPLOY
    name: Deploy Containers
    steps:
    - type: KUBERNETES_DEPLOY
      name: Upgrade Containers
      properties:
        commandName: Resize Replication Controller
        instanceCount: '33'
        instanceUnitType: PERCENTAGE
    stepsInParallel: false
  - type: VERIFY_SERVICE
    name: Verify Service
    steps:
    - type: HTTP
      name: AppDynamics
      properties:
        method: GET
        url: http://harness.io
    - type: HTTP
      name: Splunk
      properties:
        executeWithPreviousSteps: false
        method: GET
        url: https://api.harness.io
    stepsInParallel: true
    waitInterval: 10
  provisionNodes: false
  serviceName: Order
  statefulSet: false
  templateExpressions:
  - expression: ${InfraDefinition_Kubernetes}
    fieldName: infraDefinitionId
    metadata:
    - name: artifactType
      value: DOCKER
    - name: entityType
      value: INFRASTRUCTURE_DEFINITION
postDeploymentSteps:
- type: SERVICENOW_CREATE_UPDATE
  name: ServiceNow
  properties:
    STATE: In Progress
    WORK_NOTES: 'Started progress on Workflow: ${deploymentUrl}'
    issueNumber: ${snow.issueNumber}
    serviceNowAction: UPDATE_TICKET
    serviceNowCreateUpdateParams:
      action: UPDATE
      snowConnectorId: oRWA-q15SmGfKTujuJgByg
      ticketType: INCIDENT
      issueNumber: ${snow.issueNumber}
      fields:
        WORK_NOTES: 'Started progress on Workflow: ${deploymentUrl}'
        STATE: In Progress
    snowConnectorId: oRWA-q15SmGfKTujuJgByg
    ticketType: INCIDENT
preDeploymentSteps:
- type: SERVICENOW_CREATE_UPDATE
  name: ServiceNow
  properties:
    DESCRIPTION: KarlTest
    IMPACT: '2'
    SHORT_DESCRIPTION: KarTest
    URGENCY: '2'
    publishAsVar: false
    serviceNowAction: CREATE_TICKET
    serviceNowCreateUpdateParams:
      action: CREATE
      snowConnectorId: oRWA-q15SmGfKTujuJgByg
      ticketType: INCIDENT
      fields:
        URGENCY: '2'
        IMPACT: '2'
        DESCRIPTION: KarlTest
        SHORT_DESCRIPTION: KarTest
    snowConnectorId: oRWA-q15SmGfKTujuJgByg
    templateUuid: null
    templateVariables: null
    templateVersion: null
    ticketType: INCIDENT
rollbackPhases:
- type: KUBERNETES
  computeProviderName: harness-demo
  daemonSet: false
  infraDefinitionName: Prod harness-demo cluster
  name: Rollback Phase 1
  phaseNameForRollback: Phase 1
  phaseSteps:
  - type: CONTAINER_DEPLOY
    name: Deploy Containers
    phaseStepNameForRollback: Deploy Containers
    statusForRollback: SUCCESS
    steps:
    - type: KUBERNETES_DEPLOY_ROLLBACK
      name: Rollback Containers
      properties:
        className: software.wings.sm.states.KubernetesDeployRollback
        rollback: true
    stepsInParallel: false
  - type: VERIFY_SERVICE
    name: Verify Service
    phaseStepNameForRollback: Verify Service
    statusForRollback: SUCCESS
    stepsInParallel: false
  provisionNodes: false
  serviceName: Order
  statefulSet: false
  templateExpressions:
  - expression: ${InfraDefinition_Kubernetes}
    fieldName: infraDefinitionId
    metadata:
    - name: artifactType
      value: DOCKER
    - name: entityType
      value: INFRASTRUCTURE_DEFINITION
templateExpressions:
- expression: ${Environment}
  fieldName: envId
  metadata:
  - name: artifactType
    value: DOCKER
  - name: relatedField
  - name: entityType
    value: ENVIRONMENT
templatized: true
userVariables:
- type: ENTITY
  description: Variable for Environment entity
  fixed: false
  mandatory: true
  name: Environment
- type: ENTITY
  fixed: false
  mandatory: true
  name: InfraDefinition_Kubernetes
