# harness.io/skip-file-for-deploy

apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  backoffLimit: 4
  template:
    spec:
      serviceAccountName: job-sa
      restartPolicy: Never
      containers:
      - name: my-job
        image: bitnami/kubectl
        imagePullPolicy: IfNotPresent
        command:
        - /bin/bash
        - -c
        - /cmds/capture-output.sh /cmds/execute.sh
        volumeMounts:
        - name: cmds
          mountPath: /cmds
      volumes:
      - name: cmds
        configMap:
          defaultMode: 0755
          name: job-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: job-config
data:
  capture-output.sh: |
    date > /tmp/out
    $1 >> /tmp/out
    kubectl create -n {{.Values.namespace}} configmap job-output --from-file=/tmp/out
  execute.sh: |
    echo Result 1
    echo Result 2
    echo Result 3
    echo Done
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-sa
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: job-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: job-role-binding
subjects:
- kind: ServiceAccount
  name: job-sa
  namespace: {{.Values.namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-role
---
{{- if .Values.createNamespace}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.namespace}}
{{- end}}