harnessApiVersion: '1.0'
type: INFRA_DEFINITION
cloudProviderType: KUBERNETES_CLUSTER
deploymentType: KUBERNETES
infrastructure:
- type: DIRECT_KUBERNETES
  cloudProviderName: harness-demo
  namespace: harness
  releaseName: release-${infra.kubernetes.infraId}
scopedServices:
- Ingress Controller
